### ISSUE TITLE
Emojis in username not displayed 

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#27]
Custom emojis in usernames get displayed as text instead of the image. This happens for federated servers as well as the home server.

**Comment by StellaeAlis** [comment]
The same happens for custom emojis in the messages tab.

**Comment by nilathedragon** [comment]
Custom Emoji's are currently only rendered in post bodies as I had trouble figuring out how to render long displaynames with these images in them. (Layout breaking) ^_^ But definitely on the list to fix

**Comment by nilathedragon** [comment]
This is largely done across all modern app views now.
