### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#29]
Videos are not being played. For this one in particular (https://is-a.wyvern.rip/notes/9lg7l7iprpr5ghtv), there isn’t even a preview besides a gray box. 

![IMG_4470](https://github.com/Infinytum/rawr/assets/80097964/ade75394-fed9-4656-a8f4-93cd21254dd3)
![IMG_4471](https://github.com/Infinytum/rawr/assets/80097964/fce94380-5398-40ca-9e67-75d9ffd1517f)

**Comment by nilathedragon** [comment]
Right! Everything is handled as an image currently, so these files are not supported yet

**Comment by nilathedragon** [comment]
I have decided to drop the dependency I used for the gallery view (Agrume) and replace it with my own implementation as seemingly no maintained library with a decent SwiftUI API exists. This also allows rawr. to handle more media types than Videos and Images in the future!

**Comment by nilathedragon** [comment]
Testflight with the new MediaViewer is out. So Videos should now play!

Preview still won't work if the server does not provide one. So that one is still an open task

**Comment by nilathedragon** [comment]
And now previews should be handling video (And any other format really)
