### ISSUE TITLE
Not loading original post of comments

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#32]
If a comment got boosted, the parent post(s) won’t load. 

[Example](https://hessen.social/@eichkat3r/111323294552394283) 

![IMG_4475](https://github.com/Infinytum/rawr/assets/80097964/c80e1f48-7e07-45cf-bdea-3a2154905fef)

**Comment by nilathedragon** [comment]
The parent note of a reply is now shown in the detail view. It is also shown in the timeline **IF** its not a boost/renote of the reply.
