### ISSUE TITLE
Sound of videos only works if silent mode is off

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#44]
The sounds of videos is only audible if the phone is unmuted, even if the normal audio level is turned up.

I'm not sure if I just missed this until now, if it's only recently occurring, or if it's only some videos, so here's an [example](https://botsin.space/@oot_thursdays/111499151746024949) where the issue occurs for me.

**Comment by nilathedragon** [comment]
This should be fixed in the latest build
