### ISSUE TITLE
Action buttons are inconsistent in the timeline

### ISSUE THREAD

**Issue by StellaeAlis** [Infinytum/rawr#45]
- Reply: Opens post when tapped. This make sense since there's no reply function yet.
- Boost: Opens post, unable to boost from timeline directly.
- Like: Able to like/unlike a post from timeline directly.
- Reaction: Able to choose reaction from timeline directly.
- More: Able to press in timeline, but extremely small hitbox and mostly just opens post.

**Comment by nilathedragon** [comment]
Hmm I force all of them to be the same tap target size O.o

But I think I know the issue:
- Reply has no action so thats fine
- Boost is a Menu Button and not a regular button
- Like is a regular button
- Reaction is a regular button
- More is a Menu Button

My theory is that Menu Buttons somehow have a lower tap gesture priority than the tap gesture of the whole note. I have no way of influencing that priority to my knowledge.

An idea I had was to not include the Footer (Button row) in the NavigationLink to prevent this.

**Comment by StellaeAlis** [comment]
It's really weird, because I tested it with a stylus earlier and I could open the More menu in the timeline directly, but now I can't do it at all and I don't know what changed.

**Comment by nilathedragon** [comment]
IMO this could be chalked up to SwiftUI weirdness with ScrollView + LazyVStack and overlaying gestures in general...

I think excluding the button row from the navigation link will fix this. I need to redo the Note rendering anyways (backend, not the visuals) because there is lots of bugs with that.

**Comment by StellaeAlis** [comment]
Yeah, I think excluding it from the posts navigation link and giving each button their own without spacing in between might be better.

**Comment by nilathedragon** [comment]
The latest build has the action row excluded from any navigation links.
